language: java
jdk: oraclejdk8

addons:
  sonarcloud:
    organization: "nbaars-github"
    token:
      secure: $SONAR_TOKEN
cache:
  directories:
    - '$HOME/.sonar/cache'
    - '$HOME/.m2/repository'

#Test
jobs:
  include:
    - stage: build
      script:
        - mvn clean install sonar:sonar
#    - stage: sonar
#      script:
#        - sonar-scanner
